# 🤔 Array & Matrix Manipulation 🤔

**Critical**:
* Cells 5, 6
* Figure out the parameters of **reshape**

# 📚 Intro 📚

*Why Neural Net and Deep Learning?*

1. Can take in features like ML, but can obtain more sophisticated decision boundary or regression surface
1. Is capable of extracting features (from image, voice/music, text)
1. Tex & features combine into a single… blob… thing, which is used to yield the result
1. Much, much better performance with higher amounts of data, whereas with ML, the performance plateaus

Limitations of machine learning:
* Not useful while working with high-dimensional data, i.e. large number of inputs and outputs
* Cannot solve crucial aI problems like NLP, image recognition, etc.
* The process of **feature extraction** in ML is a big challenge for object/handwriting/etc. recognition
* **DEEP LEARNING TO THE RESCUE**
    * focus on the correct feaures by themselves with little guidance required from the programmer
    * DL models partially solve the dimensionality problem
    * DL essentially mimics the human brain
    * implemented through **Neural Networks** (think **brain cells**, aka biological neurons!)
    
**Deep Learning IS:** A collection of statistical ML techniques used to learn feature hierarchies often based on artificial neural networks. Multiple *"hidden layers"* at once.

Video we watched: https://www.youtube.com/watch?v=dafuAz_CV7Q

# 🏹 Vector, Matrix, & Tensor 🏹

* **Vector** - 1D tensor
* **Matrix** - 2D
* **Cube** - 3D - *like RGB! Each pixel has 3 layers for colors*
* **Vector of cubes** - 4D tensor
* **Matrix of cubes** - 5D tensor

# Make a VECTOR (a 1D tensor) in numpy!

In [1]:
import numpy as np

v = np.array([5, 2, 1]) #row vector
print(v)
print(v.shape)

[5 2 1]
(3,)


In [2]:
print(v[1])
v[1]

2


2

In [3]:
v = np.array([[5, 2, 1]]) #making a new "v" as a LIST OF LISTS
print(v.shape)

(1, 3)


In [4]:
v_t = np.transpose(v) #convert row vector to column
print(v_t)
v_t.shape

[[5]
 [2]
 [1]]


(3, 1)

In [5]:
#This will throw an error:
v[1]

IndexError: index 1 is out of bounds for axis 0 with size 1

In [6]:
#See? The RIGHT way
print(v)
print(v[0])
print(v[0][1]) #Here it is. Yes. Here

[[5 2 1]]
[5 2 1]
2


In [7]:
v.shape

(1, 3)

# Make a MATRIX (a 2D tensor) in numpy

In [8]:
v = np.array([[1,2,3],[2,0,1]])
print(v)
print(v.shape)
print(v.size)

[[1 2 3]
 [2 0 1]]
(2, 3)
6


In [10]:
v_t = np.transpose(v)
print(v_t)
print(v_t.shape)
print(v_t.size) #where n=num cols. & p = num rows, size = n*p

[[1 2]
 [2 0]
 [3 1]]
(3, 2)
6


# Arrange of Reshape the matrix (2D array or 2D tensor)

In [21]:
v = np.array([[1,2,3],[2,0,1]])
print(v.reshape(3,2)) #reshape to 3 rows and 2 col

[[1 2]
 [3 2]
 [0 1]]


In [23]:
# By applying the following reshape, we transform the matrix into 3D Tensor

print(v.reshape(3,1,2)) #Adds another dimension. 2D tensor to 3D tensor
                        #It's saying we have 3 (three) 1x2s
print(' ')
print(' ')
print(v.reshape(-1,1,2))

#Omgg
#The two reshapes above are exactly hte same
#Says "I don't care about depth" (3 and -1) but only about the 1 and 2
#So... 
#The -1 will search for the highest dimensionality it can work with
#Ahhh so the 3 just so happens to be perfect in this circumstance
#My personal conclusion: so always default to -1 as that first param!

# For some kind of neural nets, they accept certain kidns of reps of data. So the info is preserved
# but the mechanism and arrangement of neurons in those type of neural nets
# data is preserved, don't lose any info, but we're shaping it so that the
# neuron net can work with it


[[[1 2]]

 [[3 2]]

 [[0 1]]]
 
 
[[[1 2]]

 [[3 2]]

 [[0 1]]]


# Make a CUBE (a 3D tensor) in numpy

In [33]:
v = np.array([[[1.,2.,3.], [4.,5.,6.]], [[7.,8.,9.], [11.,12.,13.]]])
print(v)

print('')
print('')

#The 1st element of shape shows HOW MANY
#The 2nd and 3rd dimension

print('Read output of SHAPE like so: \'We have 2 (two) 2x3 matrices\'')
print(v.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [11. 12. 13.]]]


Read output of SHAPE like so: 'We have 2 (two) 2x3 matrices'
(2, 2, 3)


In [25]:
print(v[0])

[[1. 2. 3.]
 [4. 5. 6.]]


In [26]:
print(v[1])

[[ 7.  8.  9.]
 [11. 12. 13.]]


In [27]:
#So, we have two matrices. v[0] is the matrix in front, v[1] in back
#It's a cube of two matrices stuck together like a meatless sandwich

#This will throw an error because there is no 3rd matrix at index 2
print(v[2])

IndexError: index 2 is out of bounds for axis 0 with size 2

In [28]:
print(v.size) #number of elements

12


In [37]:
print(v.reshape(3,2,-1)) #Depth WAS 2 (2 matrices) and now it's 3 layers
#Make it into 3 layers of... wtf is the 2 and -1

[[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 11.]
  [12. 13.]]]


# Activity: Make a 2D tensor into 1D

In [38]:
v = np.array([[[1.,2.,3.], [4.,5.,6.]], [[7.,8.,9.], [11.,12.,13.]]])
print(v)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [11. 12. 13.]]]


In [41]:
print(v.reshape(1,2,-1)) #Still don't get these params

[[[ 1.  2.  3.  4.  5.  6.]
  [ 7.  8.  9. 11. 12. 13.]]]


# Make a 4D tensor in numpy

In [43]:
v = np.zeros((2, 3, 5, 5)) #So.. 2 cubes, 3 matrices each, W x L of 5x5
print(v)

[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]]


# Make 5D tensor in numpy

In [47]:
#Let's see if I've got this straight.
#2x2 matrix of cubes with depth of 3, and EACH CUBE is 5x5

#Each individual element of this ... thing ... is a 3D tensor (a cube)

v = np.zeros((2, 2, 3, 5, 5))
print(v)
print(v[0][0].shape) #3*5*5
print(v[0][1].shape) #same for all
print(v[1][0].shape)
print(v[1][1].shape)

[[[[[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]]


  [[[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]]]



 [[[[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]]


  [[[0. 0. 0. 0. 0.]
    [0. 